# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ivonne Roberts
description: > # this means to ignore newlines until "baseurl:"
  I love the feeling of hacking away at something, putting all the
  pieces together, and suddenly realizing, you’ve only scratched
  the surface of how awesome the project could really be.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ivonneroberts.com" # the base hostname & protocol for your site
twitter_username: ivlo11
github_username:  ivlo11
linkedin_username: ivonneroberts

# Build settings
markdown: kramdown
kramdown:
  input: GFM
